ERP/Areas/Hr/Controllers/ChildrenEducationController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Authentication;
using System.Web;
using System.Web.Mvc;
using log4net;
using NHibernate;
using UdvashERP.App_code;
using UdvashERP.App_Start;
using UdvashERP.Areas.Student.Controllers;
using UdvashERP.BusinessModel.Entity.Hr;
using UdvashERP.BusinessModel.Entity.UserAuth;
using UdvashERP.BusinessModel.ViewModel.Hr;
using UdvashERP.BusinessRules;
using UdvashERP.BusinessRules.CustomAttributes;
using UdvashERP.BusinessRules.Hr;
using UdvashERP.MessageExceptions;
using UdvashERP.Services.Administration;
using UdvashERP.Services.Helper;
using UdvashERP.Services.Hr;
using UdvashERP.Services.UserAuth;

namespace UdvashERP.Areas.Hr.Controllers
{
    [UerpArea("Hr")]
    [Authorize]
    [AuthorizeAccess]
    public class ChildrenEducationController : Controller
    {
        #region Logger

        private ILog _logger = LogManager.GetLogger("HrArea");

        #endregion

        #region Objects/Properties/Services/Dao & Initialization

        private readonly ICommonHelper _commonHelper;
        private List<UserMenu> authorizeMenu;
        private ISession _session;

        private readonly IOrganizationService _organizationService;
        private readonly IChildrenAllowanceSettingService _childrenAllowanceSettingService;
        private readonly IChildrenAllowanceBlockService _allowanceBlockService;
        private readonly IUserService _userService;

        public ChildrenEducationController()
        {
            _session = NHibernateSessionFactory.OpenSession();
            _commonHelper = new CommonHelper();

            _organizationService = new OrganizationService(_session);
            _childrenAllowanceSettingService = new ChildrenAllowanceSettingService(_session);
            _userService = new UserService(_session);
            _allowanceBlockService = new ChildrenAllowanceBlockService(_session);
        }

        #endregion

        #region Operational

        #region Create

        [HttpGet]
        public ActionResult Create(string message = "", int? type = 0)
        {
            try
            {
                Initialize();
                switch (type)
                {
                    case 1:
                        ViewBag.SuccessMessage = message;
                        break;
                    case 2:
                        ViewBag.ErrorMessage = message;
                        break;
                }
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                ViewBag.ErrorMessage = WebHelper.CommonErrorMessage;
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ChildrenEduViewModel childrenEduViewModel)
        {
            var messsage = "";
            try
            {
                if (ModelState.IsValid)
                {
                    authorizeMenu = (List<UserMenu>)ViewBag.UserMenu;
                    ChildrenAllowanceSetting childrenAllowanceSetting = FormModelFromVm(childrenEduViewModel);
                    _childrenAllowanceSettingService.SaveOrUpdate(authorizeMenu, childrenAllowanceSetting);
                    messsage = "Operation completed successfully";
                    return RedirectToAction("Create", new { message = messsage, type = 1 /*success*/ });
                }
                IEnumerable<ModelError> modelStateErrors = this.ModelState.Keys.SelectMany(key => this.ModelState[key].Errors);
                messsage = modelStateErrors.Aggregate(messsage, (current, modelStateError) => current + (modelStateError.ErrorMessage + " "));
                return RedirectToAction("Create", new { message = messsage, type = 2 /*failed*/ });
            }
            catch (AuthenticationException ae)
            {
                messsage = ae.Message;
            }
            catch (MessageException e)
            {
                messsage = e.Message;
            }
            catch (DuplicateEntryException dex)
            {
                messsage = dex.Message;
            }
            catch (InvalidDataException ide)
            {
                messsage = ide.Message;
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                messsage = WebHelper.CommonErrorMessage;
            }
            return RedirectToAction("Create", new { message = messsage, type = 2 /*fail*/});
        }

        #endregion

        #region Edit

        [HttpGet]
        public ActionResult Edit(long id, string message = "", int? type = 0)
        {
            ChildrenEduViewModel childrenAllowanceSettingVm = null;
            try
            {
                authorizeMenu = (List<UserMenu>)ViewBag.UserMenu;
                ChildrenAllowanceSetting childrenAllowanceSetting = _childrenAllowanceSettingService.GetChildrenAllowanceSetting(id);
                ViewBag.organizationList = new SelectList(_organizationService.LoadAuthorizedOrganization(authorizeMenu), "Id", "ShortName", childrenAllowanceSetting.Organization.Id);
                ViewBag.employmentStatus = _commonHelper.LoadEmumToDictionary<MemberEmploymentStatus>(new List<int>() { (int)MemberEmploymentStatus.Retired });
                ViewBag.paymentTypeList = new SelectList(_commonHelper.LoadEmumToDictionary<PaymentType>(new List<int>()
                        {
                            (int) PaymentType.Once,
                            (int) PaymentType.Daily
                        }), "Key", "Value", childrenAllowanceSetting.PaymentType);
                childrenAllowanceSettingVm = FormVmFromModel(childrenAllowanceSetting);
                switch (type)
                {
                    case 1:
                        ViewBag.SuccessMessage = message;
                        break;
                    case 2:
                        ViewBag.ErrorMessage = message;
                        break;
                }
            }
            catch (InvalidDataException e)
            {
                ViewBag.ErrorMessage = e.Message;
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                ViewBag.ErrorMessage = WebHelper.CommonErrorMessage;
            }
            return View(childrenAllowanceSettingVm);
        }

        [HttpPost]
        public ActionResult Edit(ChildrenEduViewModel childrenEduViewModel)
        {
            var proxyObj = new ChildrenAllowanceSetting();
            var messsage = "";
            try
            {
                if (!ModelState.IsValid)
                {
                    IEnumerable<ModelError> modelStateErrors = this.ModelState.Keys.SelectMany(key => this.ModelState[key].Errors);
                    messsage = modelStateErrors.Aggregate(messsage, (current, modelStateError) => current + (modelStateError.ErrorMessage + " "));
                    return RedirectToAction("Edit", new { message = messsage, type = 2 /*failed*/ });
                }
                authorizeMenu = (List<UserMenu>)ViewBag.UserMenu;
                proxyObj = _childrenAllowanceSettingService.GetChildrenAllowanceSetting(childrenEduViewModel.Id);
                proxyObj.Name = childrenEduViewModel.AllowanceName;
                proxyObj.Amount = childrenEduViewModel.Amount;
                proxyObj.MaxNoOfChild = childrenEduViewModel.NoOfChild;
                proxyObj.Organization = _organizationService.LoadById(childrenEduViewModel.OrganizationId);
                proxyObj.PaymentType = childrenEduViewModel.PaymentType;
                proxyObj.StartingAge = childrenEduViewModel.StartingAge;
                proxyObj.ClosingAge = childrenEduViewModel.ClosingAge;
                proxyObj.EffectiveDate = childrenEduViewModel.EffectiveFrom;
                proxyObj.ClosingDate = childrenEduViewModel.ClosingDate;
                proxyObj.IsContractual = false;
                proxyObj.IsPartTime = false;
                proxyObj.IsProbation = false;
                proxyObj.IsPermanent = false;
                proxyObj.IsIntern = false;
                foreach (var empStatus in childrenEduViewModel.EmloymentStatus)
                {
                    switch (empStatus)
                    {
                        case MemberEmploymentStatus.Contractual:
                            proxyObj.IsContractual = true;
                            break;
                        case MemberEmploymentStatus.PartTime:
                            proxyObj.IsPartTime = true;
                            break;
                        case MemberEmploymentStatus.Probation:
                            proxyObj.IsProbation = true;
                            break;
                        case MemberEmploymentStatus.Permanent:
                            proxyObj.IsPermanent = true;
                            break;
                        case MemberEmploymentStatus.Intern:
                            proxyObj.IsIntern = true;
                            break;
                    }
                }
                proxyObj.MemberEmploymentStatuses = childrenEduViewModel.EmloymentStatus;
                _childrenAllowanceSettingService.SaveOrUpdate(authorizeMenu, proxyObj);
                messsage = "Operation completed successfully";
                return RedirectToAction("Edit", new { id = proxyObj.Id, message = messsage, type = 1 /*success*/ });
            }
            catch (AuthenticationException ae)
            {
                messsage = ae.Message;
            }
            catch (MessageException e)
            {
                messsage = e.Message;
            }
            catch (NullObjectException nullObjectException)
            {
                messsage = nullObjectException.Message;
            }
            catch (InvalidDataException invalidDataException)
            {

ERP/Areas/Hr/Views/ChildrenEducation/Create.cshtml
@using UdvashERP.BusinessRules
@model UdvashERP.BusinessModel.ViewModel.Hr.ChildrenEduViewModel
@Styles.Render("~/Content/bootstrap-datetimepicker")

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title"> Children Allowance </h3>
    </div>
    <div class="panel-body">

        @using (Html.BeginForm("Create", "ChildrenEducation", FormMethod.Post, new { @id = "ceform" }))
        {

            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true)

                <div class="row">
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(model => model.OrganizationId, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.DropDownListFor(x => x.OrganizationId, (IEnumerable<SelectListItem>)ViewBag.organizationList, "--Select Organization--", new { @class = "form-control", @required = "required" })
                            @Html.ValidationMessageFor(model => model.OrganizationId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(model => model.AllowanceName, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(x => x.AllowanceName, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                            @Html.ValidationMessageFor(model => model.AllowanceName, "", new { @class = "" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-12">
                        <label class="control-label col-md-2"> Employment Status </label>
                        <label class="checkbox-inline">
                            <input type="checkbox" id="chk-employee-status" value="option1"> All
                        </label>
                        @foreach (KeyValuePair<int, string> status in ViewBag.employmentStatus)
                        {
                            <label class="checkbox-inline">
                                <input class="chk-member-status EmloymentStatus" name="EmloymentStatus" type="checkbox" value="@status.Key"> @status.Value
                            </label>
                        }
                        @Html.ValidationMessageFor(model => model.EmloymentStatus, "", new { @class = "text-danger" })
                    </div>
                    <label class="col-md-6 col-md-offset-2" id="Err-empType" style="color: red;display: none"> Please Select Employment Type</label>
                </div>


                <div class="row">
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(model => model.NoOfChild, new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(model => model.NoOfChild, new { @class = "form-control numbersOnly ", @required_name = "noOfChild", @required = "required", @minVal = 1, @number = "true", @maxlength = "2" })
                            @Html.ValidationMessageFor(model => model.NoOfChild)
                        </div>
                    </div>
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(model => model.Amount, new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control numbersOnly", @required_name = "amount", @required = "required", @minVal = 1, @number = "true", @maxlength = "15" } })
                            @Html.ValidationMessageFor(model => model.Amount)
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(model => model.StartingAge, new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(model => model.StartingAge, new { @class = "form-control numbersOnly", @required_name = "startingAge", @required = "required", @minVal = 1, @number = "true", @maxlength = "15" })
                            @Html.ValidationMessageFor(model => model.StartingAge)
                        </div>
                    </div>
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(model => model.ClosingAge, new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(model => model.ClosingAge, new { @class = "form-control numbersOnly ", @required_name = "closingAge", @required = "required", @minVal = 1, @number = "true", @maxlength = "15" })
                            @Html.ValidationMessageFor(model => model.ClosingAge)
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(model => model.PaymentType, new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.DropDownListFor(model => model.PaymentType, (IEnumerable<SelectListItem>)ViewBag.paymentTypeList, "--Select Payment--", new { @class = "form-control", @required = "required" })
                            @Html.ValidationMessageFor(model => model.PaymentType)
                        </div>
                    </div>
                    <div class="col-md-6 form-group">
                        @Html.LabelFor(model => model.EffectiveFrom, new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.EffectiveFrom, "{0:MM yyyy} ", new { htmlAttributes = new { @class = "form-control form_datetime1", @placeholder = "Effective Month", @readonly = "readonly", @Value = "" } })

                            @*@Html.TextBoxFor(model => model.EffectiveFrom, "{0:yyyy-MM-dd}", new { @class = "form-control form_datetime1", @readonly = "readonly" })*@
                            @*@Html.EditorFor(model => model.EffectiveFrom, new { htmlAttributes = new { @class = "form-control form_datetime1 ", @readonly = "readonly" } })*@
                            @Html.ValidationMessageFor(model => model.EffectiveFrom, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6 form-group">
                        <label class="control-label col-md-4"> Closing Month</label>
                        @*@Html.LabelFor(model => model.ClosingDate, new { @class = "control-label col-md-4" })*@
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.ClosingDate, "{0:MM yyyy} ", new { htmlAttributes = new { @class = "form-control form_datetime2", @placeholder = "Closing Mnth", @readonly = "readonly", @Value = "" } })
                            @*@Html.TextBoxFor(model => model.ClosingDate, "{0:yyyy-MM-dd}", new { @class = "form-control form_datetime2", @readonly = "readonly" })*@
                            @*@Html.EditorFor(model => model.ClosingDate, new { htmlAttributes = new { @class = "form-control form_datetime2 ", @readonly = "readonly" } })*@
                            @*@Html.ValidationMessageFor(model => model.ClosingDate)*@
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit" class="btn btn-primary" id="submitBtn" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap-datetimepicker")
    <script type="text/javascript" src="~/Scripts/jquery.blockUI.js"></script>
    <script src="~/Scripts/Hr/PayrollSetting/CEducation.js"></script>
    <script>

        $(document).on("change", "#EffectiveFrom", function (event) {
            var val = $("#EffectiveFrom").val();
            console.log(val);
            if (val.length > 0) {
                console.log(val + "--entry");
                $("#EffectiveFrom").next("span").remove();
                //window.showErrorMessageBelowCtrl("EffectiveFrom", "", false);
            }
        });

        $(document).ready(function () {

            $('#ceform').on('keyup keypress', function (e) {
                var keyCode = e.keyCode || e.which;
                if (keyCode === 13) {
                    OnBegin(e);
                }
            });
            $("#submitBtn").on("click", function (e) {
                OnBegin(e);
            });
        });


        function OnBegin(e) {

            /*check atleast one checkbox checked*/
            console.log("on begin callled");
            if ($("#ceform").valid()) {
                var count = 0;
                $(".chk-member-status").each(function (i) {
                    if ($(this).is(':checked')) {
                        ++count;
                    }
                });
                console.log(count);
                if (count <= 0) {
                    showErrorMessageBelowCtrl("Err-empType", "", false);
                    showErrorMessageBelowCtrl("Err-empType", "Please Select atleast one Employee Type", true);
                    $('#ceform').submit(function () {
                        return false;
                    });
                } else {
                    console.log("submit form ");
                    showErrorMessageBelowCtrl("Err-empType", "", false);
                    $('#ceform')[0].submit();
                }

            } else {
                // return false;
            }
        }

        $('.form_datetime1').datetimepicker({
            format: "MM yyyy",
            autoclose: true,
            startView: "year",
            minView: "year",
            maxView: 4
        }).on('changeDate', function (ev) {
            window.showErrorMessageBelowCtrl("EffectiveFrom", "", false);
            if ($(this).val().length <= 0) {
                window.showErrorMessageBelowCtrl("EffectiveFrom", "Please Enter Effective Date", true);
            } else {
                window.showErrorMessageBelowCtrl("EffectiveFrom", "", false);
            }
        });

        $('.form_datetime2').datetimepicker({
            format: "MM yyyy",
            autoclose: true,
            startView: "year",
            minView: "year",
            maxView: 4
        });

    </script>
}

ERP/Areas/Hr/Views/ChildrenEducation/Details.cshtml
@using UdvashERP.BusinessRules
@using UdvashERP.BusinessRules.Hr
@model UdvashERP.BusinessModel.ViewModel.Hr.ChildrenAllowanceSettingDetailsVm
@Styles.Render("~/Content/bootstrap-datetimepicker")
@{
    ViewBag.Title = "C/E Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">Children Allowance Setting</div>
    </div>
    <div class="panel-body">
        <div class="form-horizontal">
            <div class="form-group">
                @Html.Label("Organization: ", new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.OrganizationName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
                @Html.Label("Settings Name: ", new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.AllowanceName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    <label class="control-label col-md-2"> Employment Status </label>
                    @foreach (MemberEmploymentStatus eStatus in ViewBag.EmploymentStatusList)
                    {
                        if (Model.EmloymentStatus.Contains(eStatus))
                        {
                            <label class="checkbox-inline">
                                <input name="EmployeeStatuses" type="checkbox" disabled checked="checked" value="0"> @eStatus
                            </label>
                        }
                        else
                        {
                            <label class="checkbox-inline">
                                <input name="EmployeeStatuses" disabled type="checkbox" value="0"> @eStatus
                            </label>
                        }
                    }

                </div>
            </div>

            <div class="form-group">
                @Html.Label("Max No of Children :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.NoOfChild, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
                @Html.Label("Amount :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Starting Age :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.StartingAge, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
                @Html.Label("Closing Age :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.ClosingAge, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Payment Type :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @if (Model.PaymentType == Convert.ToInt16(PaymentType.Daily).ToString())
                    {
                        <input class="form-control" type="text" value="Daily" readonly="readonly" />
                    }
                    else if (Model.PaymentType == Convert.ToInt16(PaymentType.Monthly).ToString())
                    {  <input class="form-control" type="text" value="Monthly" readonly="readonly" />}
                    else if (Model.PaymentType == Convert.ToInt16(PaymentType.Once).ToString())
                    {  <input class="form-control" type="text" value="Once" readonly="readonly" />}
                    else if (Model.PaymentType == Convert.ToInt16(PaymentType.Yearly).ToString())
                    { <input class="form-control" type="text" value="Yearly" readonly="readonly" /> }
                    else
                    {
                        <input class="form-control" type="text" value="N/A" readonly="readonly" />
                    }

                    @*@Html.EditorFor(model => model.PaymentType, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })*@
                </div>
                @Html.Label("Effective From :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.EffectiveFrom, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Closing Date :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.ClosingDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Create By :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.CreateBy, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Creation Date :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.CreationDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Modified By :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.ModifiedBy, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Modified Date :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.EditorFor(model => model.ModificationDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                </div>
            </div>
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Back to List", "ManageChildrenEducationAllowance", "ChildrenEducation")
</p>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}